stages:
  - develop

deploy:
  type: develop
  before_script:
    - mkdir -p ~/.ssh
    # Paste the PRIVATE key into a gitlab variable. Pay attention to the linebreak at the end when pasting
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'kakumei.jp' >> ~/.ssh/known_hosts
    - ssh fuji@kakumei.jp "cd $DEPLOY_PATH && git pull"
  script:
    - python -V
  only:
    - master
